### ISSUE TITLE
Create Test 2 / "local service not impacted" e2e test

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes-sigs/mcs-api#16]
Per the KEP, an e2e test must exist that tests:

> Test cluster A local service not impacted by same-name imported service.

We define "not impacted" as:

> Not impacted = when you run a Service in cluster A called `foo`, and you have a ServiceImport for `foo`, you can still resolve `foo.ns.svc.cluster.local` and and its IP is different from the ServiceImport IP and when you actually request the local service IPs you get a response back and its the right response (so we have to make the response smart, such as reporting their clusterID)
> `foo.ns.svc.clusterset.local` will sometimes return clusterB
> `foo.ns.svc.cluster.local` will always (always=50 times in a row) return cluster A

Given a setup with two clusters, this test should do the following:

* Service is in ClusterA, NOT exported
    * can hit it with cluster.local
* Service is in ClusterB and exported
    * can hit it with clusterset.local, always reports ClusterB
* Also Export the Service in ClusterA 
    * can hit it with clusterset.local, sometimes will say ClusterB, sometimes will say ClusterA
* Hit it 50 times, if I get at least one from either we good
    * Can still hit it with cluster.local, will ALWAYS say its from clusterA
    * No other services should be responding
        * Relevant because if the SUT happens to have other clusters participating and they get all up in there, we want to report that

See the [existing connectivity test](https://github.com/kubernetes-sigs/mcs-api/blob/master/e2etest/connectivity_test.go) for inspiration on setup and potential request and response pods. Notably in this case the response needs to be smart enough to share what cluster it is in.

**Comment by lauralorenz** [comment]
/assign lauralorenz
@knee-berts is helping me with this one

**Comment by nojnhuh** [comment]
Sorry @lauralorenz didn't catch that you were already assigned to this. Don't mean to step on your toes, but happy to pick this up!

**Comment by nojnhuh** [comment]
@lauralorenz Just to clarify since these tests involve setting up DNS, is compiling our own CoreDNS with https://github.com/coredns/multicluster and configuring that for kind the recommended approach? Are there any other steps required to make the `clusterset.local` domain reachable?

**Comment by nojnhuh** [comment]
> @lauralorenz Just to clarify since these tests involve setting up DNS, is compiling our own CoreDNS with https://github.com/coredns/multicluster and configuring that for kind the recommended approach? Are there any other steps required to make the `clusterset.local` domain reachable?

I think I got this working here: #50
