### ISSUE TITLE
Is there a easy way to install mcs-api

### ISSUE THREAD

**Issue by qingwave** [kubernetes-sigs/mcs-api#27]
Now we can only install mcs-api via demo script, is there any stable way to install it kustomize or helm package?

**Comment by RainbowMango** [comment]
Do you mean `ServiceExport` and `ServiceImport`?
https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/multicluster.x-k8s.io_serviceexports.yaml
https://github.com/karmada-io/karmada/blob/master/charts/karmada/_crds/bases/multicluster.x-k8s.io_serviceimports.yaml

**Comment by qingwave** [comment]
Both CRDs and controller

**Comment by RainbowMango** [comment]
Here is a controller for the demo. 
https://github.com/kubernetes-sigs/mcs-api

**Comment by qingwave** [comment]
> Here is a controller for the demo. https://github.com/kubernetes-sigs/mcs-api

Read the [[KEP-1645](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api)] again, this project only aim to define the service discorvery spec cross clusters without detail implemention. Is this right? Please correct me if I miss something.

**Comment by RainbowMango** [comment]
Yes, you are right. But there is a controller in the repo, which is just for demo.

**Comment by qingwave** [comment]
@RainbowMango Thanks for your explanation, now it's more clear to me.
