### ISSUE TITLE
scripts/up.sh failed add routes to clusters

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes-sigs/mcs-api#3]
**What happened**:
I'm trying to run the demo but seems the clusters can not get ready.

**What you expected to happen**:
```
# ./scripts/up.sh
...
Connecting cluster networks...
Connecting cluster c1 to c2.kubeconfig
Command line is not complete. Try option "help"
```
**How to reproduce it (as minimally and precisely as possible)**:
- run command `make docker-build`.
- run command `./scripts/up.sh`

**Anything else we need to know?**:
```
# kind version
kind v0.9.0 go1.15.2 linux/amd64
```

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-dirty", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"dirty", BuildDate:"2020-11-02T09:52:18Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- OS (e.g: `cat /etc/os-release`):
```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by RainbowMango** [comment]
This might be the `kubectl` bug addressed by [this PR](https://github.com/kubernetes/kubernetes/pull/98057).
Let's see what shall we do.
cc @JeremyOT

**Comment by RainbowMango** [comment]
```
kubectl --kubeconfig c2.kubeconfig get nodes -o jsonpath='{range .items[*]}ip route add {.spec.podCIDR} via {.status.addresses[?(.type=="InternalIP")].address}{"\n"}'
ip route add 10.12.0.0/24 via 172.18.0.3
ip route add  via  // Here is an empty result
```

**Comment by atiratree** [comment]
> kubectl --kubeconfig c2.kubeconfig get nodes -o jsonpath='{range .items[*]}ip route add {.spec.podCIDR} via {.status.addresses[?(.type=="InternalIP")].address}{"\n"}'

@RainbowMango the range is not using a correct syntax and is missing an {end} element.

Please see https://kubernetes.io/docs/reference/kubectl/jsonpath/

posted a PR for reverting the original fix https://github.com/kubernetes/kubernetes/pull/104172
