### ISSUE TITLE
Tag an official release

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/mcs-api#5]
Currently implementations need to import by `v0.0.0-20200908023942-d26176718973` in golang. It would be nice to have a official tagged release to import by. https://github.com/kubernetes-sigs/gateway-api has done this

**Comment by RainbowMango** [comment]
cc @JeremyOT

**Comment by JeremyOT** [comment]
Good idea! I just tagged v0.1.0 with the current state of v1alpha1
