### ISSUE TITLE
Conformance test: importing services

### ISSUE THREAD

**Issue by skitt** [kubernetes-sigs/mcs-api#66]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#importing-services

Using DNS (since accessing exported services relies on DNS), check that:

- [x] Exporting a ServiceExport results in the creation of a corresponding ServiceImport in each importing cluster hosting the corresponding namespace
- [ ] Importing clusters without the corresponding namespace don’t get a ServiceImport (the namespace may be created automatically, so the test can’t assume that because it hasn’t created the namespace, the namespace doesn’t exist)
- [x] ServiceImports only exist as long as at least one corresponding source ServiceExport exists
- [x] EndpointSlices are labeled as follows: “multicluster.kubernetes.io/service-name” pointing to the ServiceImport, “multicluster.kubernetes.io/source-cluster” pointing to the source cluster

**Comment by tpantelis** [comment]
> * [ ]  Exporting a ServiceExport results in the creation of a corresponding ServiceImport in each importing cluster hosting the corresponding namespace

This was done as part of https://github.com/kubernetes-sigs/mcs-api/pull/64.

> * [ ]  Importing clusters without the corresponding namespace don’t get a ServiceImport (the namespace may be created automatically, so the test can’t assume that because it hasn’t created the namespace, the namespace doesn’t exist)

This test would have to be optional and should first wait a reasonable of time for the namespace to be created and, if not, then skip the test. It can also have a specific label (eg "Namespace") so users can skip it if they know their implementation doesn't support auto-creating namespaces.

> * [ ]  EndpointSlices are labeled as follows: “multicluster.kubernetes.io/service-name” pointing to the ServiceImport, “multicluster.kubernetes.io/source-cluster” pointing to the source cluster

This should be covered by https://github.com/kubernetes-sigs/mcs-api/issues/70.

**Comment by skitt** [comment]
> > * [ ]   Importing clusters without the corresponding namespace don’t get a ServiceImport (the namespace may be created automatically, so the test can’t assume that because it hasn’t created the namespace, the namespace doesn’t exist)
> 
> This test would have to be optional and should first wait a reasonable of time for the namespace to be created and, if not, then skip the test. It can also have a specific label (eg "Namespace") so users can skip it if they know their implementation doesn't support auto-creating namespaces.

The test isn’t about automatically created namespaces; all it’s supposed to do is verify that clusters without a given namespace don’t get the corresponding ServiceImports. I suspect I came up with this based on Submariner’s old behaviour; in practice if the namespace doesn’t exist then the ServiceImport can’t either! The parenthetical about automatically-created namespaces is a caveat, that’s all.

So really this test is nonsensical and should be ignored.

**Comment by tpantelis** [comment]
> ServiceImports only exist as long as at least one corresponding source ServiceExport exists

This was done by #82 so this issue is complete and can be closed.

**Comment by skitt** [comment]
Fantastic, thanks!
