### ISSUE TITLE
Conformance test: ClusterSetIP

### ISSUE THREAD

**Issue by skitt** [kubernetes-sigs/mcs-api#68]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#clustersetip

Check that ClusterSetIP-type ServiceImports have an associated IP address which is accessible from the importing cluster.

**Comment by tpantelis** [comment]
This was done as part of https://github.com/kubernetes-sigs/mcs-api/pull/64.

**Comment by tpantelis** [comment]
> This was done as part of #64.

@skitt This issue can be closed.
