### ISSUE TITLE
Conformance test: EndpointSlices

### ISSUE THREAD

**Issue by skitt** [kubernetes-sigs/mcs-api#70]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#endpointslice

Check that:

- [ ] EndpointSlices are created for each exporting cluster; any single EndpointSlice only contains endpoints from a single exporting cluster
- [ ] EndpointSlices have owner references pointing to their ServiceImport

**Comment by tpantelis** [comment]
You can assign this to me.

**Comment by tpantelis** [comment]
We should also check that `EndpointSlices` are labeled as follows:

- `multicluster.kubernetes.io/service-name` pointing to the `ServiceImport`
- `multicluster.kubernetes.io/source-cluster` pointing to the source cluster
- `endpointslice.kubernetes.io/managed-by` pointing to something other than `endpointslice-controller.k8s.io`

**Comment by tpantelis** [comment]
> EndpointSlices are created for each exporting cluster; any single EndpointSlice only contains endpoints from a single exporting cluster

I'm nor sure how we can verify this.
