### ISSUE TITLE
Conformance test: service ports

### ISSUE THREAD

**Issue by skitt** [kubernetes-sigs/mcs-api#71]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-multicluster/1645-multi-cluster-services-api/README.md#service-port

Check that Services exported on different ports have the union of service ports exposed.

**Comment by MrFreezeex** [comment]
As I had to implement the port merging recently there is two edge cases that are not very explicit in the KEP that could be checked here:
- Two service ports have the same name in different clusters, something like that:
cluster A:
```
- name: foo
  port: 80
```
cluster B:
```
- name: foo
  port: 8000
```

- Two similar services with different names
cluster A:
```
- name: foo
  port: 80
```
cluster B:
```
- name: bar
  port: 80
```
